### ISSUE TITLE
Can't add Int.max.seconds to date

### ISSUE THREAD

**Issue by Koshub** [naoty/Timepiece#11]
Probably this is `dateByAddingUnit` problem

**Comment by naoty** [comment]
@Koshub Please let me know more information. I tried `(now + Int.max.seconds).stringFromFormat("yyyy-MM-dd")` and the result was `2558-05-16`.

**Comment by Koshub** [comment]
@naoty  Please, check out the result in this example:
```swift
let now = NSDate()
let result = now + Int.max.seconds
println("now \(now) result \(result)")
// now 2015-05-16 14:45:21 +0000 result 2015-05-16 14:45:21 +0000
```

**Comment by naoty** [comment]
@Koshub Thank you reporting! I also can reproduce this problem. If it is solved, I let you know that.

**Comment by naoty** [comment]
@Koshub Do you want `NSDate.distantFuture()`?, don't you? Maybe, `Int.max.seconds.later` doesn't work because it is greater than the max of NSDate value.

**Comment by Koshub** [comment]
@naoty  Well, I don't know if there should be `NSDate.distantFuture()`. Probably, yes. It's up to you to decide. I think it shouldn't be the same date and `NSDate.distantFuture()` is a good choice.

**Comment by naoty** [comment]
I think this library don't need to provide the alternative to `NSDate.distantFuture()`. @Koshub, would you use `NSDate.distantFuture()` or `NSDate.distantPast()`?

**Comment by Koshub** [comment]
@naoty  Yes, I will. Although using `NSDate.distantFuture()` or `NSDate.distantPast()` is a good choice, it is not the best way to solve this problem. But I think we can use them because of the `NSDate` type restrictions.
