### ISSUE TITLE
Mac OS X support.

### ISSUE THREAD

**Issue by danielmartinprieto** [naoty/Timepiece#18]
Hi! Could you add Carthage support for Mac OS X? I don't know how to do it, but if you explain to me I can try and do a pull request.

Thanks.

**Comment by naoty** [comment]
@danielmartinprieto Hi! Have you read [this page](https://github.com/Carthage/Carthage#if-youre-building-for-os-x) yet? This library supports Carthage. If you follow the page, you can integrate this library into your OS X project. If not works, please let me know.

**Comment by danielmartinprieto** [comment]
Yes, I've added it to my project, but it didn't generate the Mac OS X build, only the iOS one. So I guess something is missing in the configuration of the project.

Thanks.

**Comment by danielmartinprieto** [comment]
Hi, @naoty. Did you get my message?

Thanks.

**Comment by naoty** [comment]
@danielmartinprieto Sorry for the delay. I will try to reproduce the problem. But, I have no experience to develop an OS X application and so I really appreciate you if you send a pull request to solve it.

**Comment by danielmartinprieto** [comment]
@naoty OK, will try to do it in some hours.

**Comment by naoty** [comment]
@danielmartinprieto Would you try to use `osx-carthage-support` branch? This branch works well at my sample OSX application.

**Comment by danielmartinprieto** [comment]
@naoty it seems that it works.

**Comment by naoty** [comment]
@danielmartinprieto Thanks! I will merge this branch and close this issue and your PR.
