### ISSUE TITLE
Swift 2.0, cocoapods 0.39.0 pod issue

### ISSUE THREAD

**Issue by crarau** [naoty/Timepiece#42]
Using swift 2.0 with Cocoapods 0.39.0 I'm getting the issue below:

Pre-downloading: `Timepiece` from `https://github.com/naoty/Timepiece.git`, branch `swift-2`
fatal: No names found, cannot describe anything.
[!] Unable to satisfy the following requirements:
- `Timepiece (from `https://github.com/naoty/Timepiece.git`, branch `swift-2`)` required by `Podfile`

Thx

**Comment by naoty** [comment]
@crarau Sorry for confusion. The support for swift 2.0 has been already merged  into `master`. So, You should use `master`. Just now, I deleted `swift-2` branch.

**Comment by crarau** [comment]
Yes, using master fixes the issue! 
Thanks!

**Comment by retroneo** [comment]
I cannot use Master either now.
Pre-downloading: `Timepiece` from `https://github.com/naoty/Timepiece.git`
fatal: No names found, cannot describe anything.
[!] Unable to satisfy the following requirements:
- `Timepiece (from `https://github.com/naoty/Timepiece.git`)` required by `Podfile`

**Comment by naoty** [comment]
Just now, I successfully installed Timepiece by following Podfile. I use cocoapod 0.39.0 and ruby 2.2.2.

```rb
source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

pod "Timepiece"
```

@retroneo, would you let me know about your environment such as versions and Podfile?

**Comment by retroneo** [comment]
use_frameworks!
platform :ios, '9.1'
platform :watchos, '2.0'
pod 'Timepiece', :git => 'https://github.com/naoty/Timepiece.git'

**Comment by naoty** [comment]
@retroneo Fixed. Would you try to install?

**Comment by retroneo** [comment]
Excellent. Now working. Thanks.
