### ISSUE TITLE
Question: How to import this?

### ISSUE THREAD

**Issue by goktugyil** [naoty/Timepiece#45]
What is the best way to import this library after installing with pods?

Do you use import Timepiece in every swift file that needs to use this? Is there a way to globally import it for everything?

Thanks

**Comment by naoty** [comment]
I have never use Timepiece in any iOS projects. But, if I use it, I will import it in every files. It looks like Java.

**Comment by goktugyil** [comment]
Are you using on tvOS? Doesn't it work in Xcode in either way?

**Comment by naoty** [comment]
I'm not using on any devices. Have you try `tvOS` branch?

**Comment by goktugyil** [comment]
No, I only tried it in an iOS project from the main branch. Actually my question is not specific to this library only, my question is kind of general on how to import libraries that are like this one.

**Comment by naoty** [comment]
If your question is not specific to this library, please ask it somewhere else.
