### ISSUE TITLE
How can I check format of string

### ISSUE THREAD

**Issue by Jirka1111** [naoty/Timepiece#47]
Is there a simple way how can I check a format of string variable?

Example:

if(stringVariable.format == format("dd/MM/yyyy"){
    print("format of stringVariable is the same as date!")
}

**Comment by naoty** [comment]
@Jirka1111 I don't know it. Do you ask the question about Timepiece or Swift?

**Comment by Jirka1111** [comment]
I am sorry, the question belongs to another library.
