### ISSUE TITLE
Value of type 'Int' has no member 'weeks', 'seconds', …

### ISSUE THREAD

**Issue by skofgar** [naoty/Timepiece#52]
Hi I have the weird error, that whenever I add `'Timepiece'`, I get the error, that the type 'Int' does not have a member for week, seconds etc. However, I can see the Pod files in the workspace in the Pods-project. (Especially the `Int+Timepiece.swift`-file is there.) All my other Pods work...

Do you have an idea what it could be?

My Podfile looks like this.. not really spectacular.
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

xcodeproj 'MyProject'

use_frameworks!

target 'MyProject' do
    pod 'GoogleMaps'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Alamofire', '~> 3.1.5'
    pod 'Hex', '~> 3.0'
    pod 'AFNetworking', '~> 2.6.0' #'~> 2.4'
    pod 'BlockRSSParser', '~> 2.1'
    pod 'Parse'
    pod 'Timepiece'
end
```

**Comment by naoty** [comment]
@skofgar Thank you for reporting. I tried it just now. But, I successfully built codes such as `1.day.ago`. I wonder why you got that error.

**Comment by skofgar** [comment]
Hmm. Ok. I'll tried it in a new project too.. I'll try again and get back to you asap.

**Comment by skofgar** [comment]
@naoty I discovered the problem.
So silly... - I forgot to add `import Timepiece`.
