### ISSUE TITLE
How to subtract 2 dates and get minutes?

### ISSUE THREAD

**Issue by basememara** [naoty/Timepiece#53]
Great library, thanks a mil!! Works beautifully for watch complications ;)

I'm trying to subtract 2 dates and get minutes. I couldn't find how to do this. What I was hoping for was something like this:

```
(date1 - date2).minutes
(date1 - date2).hours
(date1 - date2).days
```
This doesn't compile for `Timepiece` of course, so what I'm ending up doing is this:
```
NSCalendar.currentCalendar().components(.Minute,
  fromDate: date1, toDate: date2, options: []).minute`
```
Is something like this possible with `Timepiece`?

**Comment by naoty** [comment]
@basememara Thank you for using this library! `date1 - date2` returns `NSTimeInterval`. So, you can get `second`, `minute`, `hour`, `day`, but cannot get `month` and `year` correctly because the days of one month is not constant.

**Comment by basememara** [comment]
How about something like this?
```
public extension NSTimeInterval {
    
    public var seconds: Int {
        return Int(self)
    }
    
    public var minutes: Double {
        return self / 60.0
    }
    
    public var hours: Double {
        return self / 3600.0
    }
    
    public var days: Double {
        return self / 86400.0
    }
    
}
```

**Comment by naoty** [comment]
@basememara It looks good! These operators also can be used but they are deprecated because they are incorrect as I said.

```swift
if date1 - date2 < 4.hours {
    // Do something
}
```

**Comment by naoty** [comment]
@basememara I'll close this issue but if you are still in trouble, I'll reopen.
