### ISSUE TITLE
"No such module 'Timepiece'"

### ISSUE THREAD

**Issue by pketh** [naoty/Timepiece#54]
Hi, I'm pretty new to Swift/pods. I added timepiece to my pod file, installed it and can verify it's added to my app. But attempting to `import Timepiece` at the top of my appDelegate with the rest of my other imports gives me an error `"No such module 'Timepiece'"`

Any idea what I'm missing here?

Thanks!

**Comment by pketh** [comment]
Hmm, I also get the same error when I run the included `timepiece.playground`. I'm on XCode 7.3

**Comment by naoty** [comment]
@pketh Thank you for using my library. Do you open *.xcworkspace, not *.xcodeproj? Is your problem specific to Timepiece?

**Comment by pketh** [comment]
Thanks for the quick reply :)
Yeah I'm using xcworkspace and other pods do import. If it helps, I'm making a Mac app. But didn't do anything Mac specific in the playground file

**Comment by naoty** [comment]
@pketh I created a sample OSX application using Timepiece, and successfully built the app. The repository is [here](https://github.com/naoty/SampleOSXApp). What is the difference with yours?

**Comment by pketh** [comment]
If I download your sample application directly and open it in xcode, going to the appDelegate shows the same error. Comparing our appDelegate files, they look like they have pretty much the same init. My project is https://github.com/pketh/weather-cat . 

That being said, I've since found a workaround, so if I'm the only person who's had this issue I wouldn't bother trying too hard to track it down :) If other osx users bring this up, maybe file that as a duplicate issue.

Thanks Noato!

**Comment by pketh** [comment]
Looks like this was the issue http://stackoverflow.com/questions/29500227/xcode-no-such-module-error-but-the-framework-is-there , just had to flip this guy to `Yes`..

![screen shot 2016-04-04 at 8 45 17 pm](https://cloud.githubusercontent.com/assets/877072/14268191/362e343e-faa6-11e5-96fb-2024f52e6388.png)

**Comment by naoty** [comment]
It's a pleasure for you to solve the problem!
