### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by hdoria** [naoty/Timepiece#60]
Any plans to support Swift 3.0?

**Comment by reidmain** [comment]
@naoty are you able to comment on this? I know there are a lot of developers looking for Swift 3 support for all their dependencies now that Xcode 8 GM has been released.

**Comment by hijamoya** [comment]
need swift 3.0 support!!

**Comment by skofgar** [comment]
@hijamoya, @hdoria: Until @naoty addressed the issue feel free to use my branch, for which I created a [merge request](https://github.com/naoty/Timepiece/pull/59).

**Comment by reidmain** [comment]
@skofgar I have been and it has been working great.
