### ISSUE TITLE
0.6.0 is not compatible with 0.5.0

### ISSUE THREAD

**Issue by RyogaK** [naoty/Timepiece#62]
0.6.0 can run in Swift3 only, so it's not compatible with 0.5.0.
If you would like to follow semantic versioning as Carthage suggested, you can change the version to 1.0.0.
If you don't, we can't use `~>` operator of Cartfile.

You can see about the versioning in the document https://github.com/Carthage/Carthage if you would like to know more.

Thanks.

**Comment by naoty** [comment]
I have not released stable versions yet. So, as http://semver.org/spec/v2.0.0.html#spec-item-4 said, I don't assure backward compatibility.
