### ISSUE TITLE
syntactic sugar for week days

### ISSUE THREAD

**Issue by Evertt** [naoty/Timepiece#72]
With something like this:

```swift
enum Weekday { case monday, tuesday, wednesday, thursday, friday, saturday, sunday }

extension Date {
   static func next(weekday: Weekday) -> Date {
        // some code
    }

   static func last(weekday: Weekday) -> Date {
        // some code
    }
}
```

you can write things like:

```swift
func wait(until: Date) {}

wait(until: .next(.wednesday))
```

**Comment by naoty** [comment]
What date does `.next(.wednesday)` return?

**Comment by Evertt** [comment]
A date, as you can see in my example code. More specifically, it would return next wednesday at 12:00 AM, just like `.tomorrow` returns 12:00 AM tomorrow.

**Comment by naoty** [comment]
I see. I think the usecase where you want to get the next/last Wednesday is a bit rare. So, if there are many requests for this feature, I will consider this feature.
