### ISSUE TITLE
Weekend

### ISSUE THREAD

**Issue by kwstasna** [naoty/Timepiece#76]
Hello.
Very nice lib. it rocks man!
Just wandering if there is any quick workaround to take the dates of the next weekend (saturday-sunday)
like `Date.today()`

**Comment by naoty** [comment]
@kwstasna Thanks! Now, there isn't such a feature.

**Comment by naoty** [comment]
@kwstasna I added methods to realize your request at https://github.com/naoty/Timepiece/pull/77.

```swift
let nextSaturday = Date().changed(weekday: 7)
let nextSunday = 1.week.later.changed(weekday: 1)
```

**Comment by kwstasna** [comment]
This is a very good approach but i meant another thing.

Lets say that today is Thursday 8-12-2016...
and i want to get the dates of this weekend that comes up, which means 10 and 11 - 12 - 2016.

**Comment by naoty** [comment]
This new method returns the dates of this weekend.

<img width="1008" alt="2016-12-09 22 34 04" src="https://cloud.githubusercontent.com/assets/413899/21050723/bd4c7b9c-be5f-11e6-97b5-96cce990b855.png">

**Comment by naoty** [comment]
@kwstasna I will close this issue. But if your question is not solved yet, I will reopen this.
