### ISSUE TITLE
Date comparing

### ISSUE THREAD

**Issue by Koshub** [naoty/Timepiece#8]
Thanks for perfect abstraction like now + 2.days. It will be fantastic if you add dates comparing!

**Comment by naoty** [comment]
@Koshub I also want to compare dates. I try to add it!

**Comment by Koshub** [comment]
@naoty nice, looking forward to it :+1:

**Comment by naoty** [comment]
@Koshub I have added it at 9ed880f0350f15a567d04f64b8c318a106127787 and released as `0.3.0`! Please try to compare dates.

**Comment by Koshub** [comment]
@naoty  Thanks. Although there are not all operators (like <,>,>=,<=,==,!=) this is better than nothing. Thanks again

**Comment by naoty** [comment]
@Koshub All operators are supported because `Equatable` protocol, which requires `<`,  and `Comparable` protocol, which requires `==`, is implemented. Look at [tests](https://github.com/naoty/Timepiece/blob/master/Tests/NSDate+TimepieceTests.swift#L43)!

**Comment by Koshub** [comment]
@naoty Sorry. I didn't know about that.

**Comment by naoty** [comment]
@Koshub Thank you for the issue!
