### ISSUE TITLE
changing timezone

### ISSUE THREAD

**Issue by Tripwire999** [naoty/Timepiece#81]
Hi,

I noticed that in the newer versions the change method is removed. Normally to change the timezone i would do something like this:
```swift 
Date().change(timeZone: TimeZone(name: "UTC")!)
```

How can I do this with the latest Timepiece?

**Comment by naoty** [comment]
@Tripwire999 Sorry. I removed a feature to change time zone because it was a little buggy. Also, it was not compatible with Linux because it was implemented using Objective-C runtime APIs.

**Comment by naoty** [comment]
@Tripwire999 I will close this issue. But, if your question is not solved yet, I will reopen this.
