### ISSUE TITLE
time ago support

### ISSUE THREAD

**Issue by Prince2k3** [naoty/Timepiece#85]
Be nice to have time ago support with this library. If there is one I didn't see where it was.

But being able to say `date.timeAgo` that outputs "4 minutes ago"  etc...

**Comment by naoty** [comment]
Thank you for the issue!

The timeago feature requires localization such as "4分前" in Japanese. But, I don't want to support localization in Timepiece because I want to keep Timepiece a simple wrapper for Foundation.

If I implement the feature, I will build another library which just does it.

**Comment by Prince2k3** [comment]
You make a good point about localization. Time ago feature though very simple can be complex with localization.

**Comment by naoty** [comment]
I will close this issue. But, if you still have any reason to implement this feature, feel free to post messages.
